name: ci 
on:
  push:
    branches:
      - master 
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-exclude
      - run: pip install mdx_truly_sane_lists
      - run: pip install mike
      - name: Git Config
        run: git config user.name bofa1exx && git config user.email bofa1exx@gmail.com
      - name: Mike Deploy master
        run: |
          # mike delete master -p
          git fetch origin gh-pages --depth=1 # fix mike's CI update
          mike list
          mike deploy master -p --rebase
          mike list
