name: release

on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Library build and publish
        uses: MathieuSoysal/Java-maven-library-publisher@v1.0.3
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus-username: ${{ secrets.OSSRH_USER }}
          nexus-password: ${{ secrets.OSSRH_PASSWORD }}
          java-version: 8
